language: android
sudo: required
dist: trusty
jdk: oraclejdk8
os:
  - linux

before_install:
  - export ANDROID_HOME=~/android-sdk-linux
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip
  - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  # Silence warning.
  - mkdir -p ~/.android
  - touch ~/.android/repositories.cfg
  - HOMEBREW_NO_AUTO_UPDATE=1
  - yes | sdkmanager --licenses
  - sdkmanager "emulator" "tools" "platform-tools" > /dev/null
  - sdkmanager --list | head -15
  # install older packages (for emulator)
  - sdkmanager "build-tools;25.0.2" "platforms;android-25" > /dev/null
  # Create and start emulator.
  - sdkmanager "system-images;android-25,google_apis;armeabi-v7a" > /dev/null
  - sdkmanager --list | head -15
  - echo no | avdmanager create avd --force -n test -k "system-images;android-25,google_apis;armeabi-v7a";$ABI"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -gpu swiftshader &
before_script:
  # Wait for emulator to startup.
  - ./scripts/android-wait-for-emulator.sh
  - adb shell input keyevent 82

script:
  - ./gradlew connectedAndroidTest
