dist: trusty
jdk: oraclejdk8
language: android

android:
  components:
    - extra
    - android-29
    - build-tools-29.0.2

before_install:
 - chmod +x gradle
  
script:
 - ./gradle connectedAndroidTest
